# Generated by Django 5.0.5 on 2024-05-25 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disease", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvdata",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="modelresult",
            name="file_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="csvdata",
            name="date",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="modelresult",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="modelresult",
            name="label",
            field=models.CharField(max_length=255),
        ),
    ]
