# Generated by Django 5.0.5 on 2024-05-25 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disease", "0002_csvdata_created_at_modelresult_file_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="csvdata",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="csvdata",
            name="date",
        ),
        migrations.RemoveField(
            model_name="csvdata",
            name="feed",
        ),
        migrations.RemoveField(
            model_name="csvdata",
            name="length",
        ),
        migrations.RemoveField(
            model_name="csvdata",
            name="weight",
        ),
        migrations.AddField(
            model_name="csvdata",
            name="file_path",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="csvdata",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
